AWSTemplateFormatVersion: 2010-09-09
Description: Setup for Photo-Forum

Resources:
  ContentsBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
  WebhostingBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Delete
  WebHostingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: WebHostingS3BucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref WebhostingBucket
                - /*
      Bucket: !Ref WebhostingBucket


  ForumUsersGroup:
    Type: AWS::IAM::Group
    Description: Forum-Users
    Properties:   
      GroupName: !Join
        - "-"
        - - "ForumUsers"
          - !Ref AWS::Region
      ManagedPolicyArns:
        - !Ref PolicyShowAllBucketsOnConsole
        - !Ref PolicyListObjectsInBucketRoot
        - !Ref PolicyListObjectsInConfig
        - !Ref PolicyListFoldersInOpenChannels
        - !Ref PolicyListObjectsInOpenChannels
        - !Ref PolicyObjectCreationInOpenChannels

  ForumAdminsGroup:
    Type: AWS::IAM::Group
    Description: Forum-Admins (Moderators)
    Properties:   
      GroupName: !Join
        - "-"
        - - "ForumAdmins"
          - !Ref AWS::Region
      ManagedPolicyArns:
        - !Ref PolicyShowAllBucketsOnConsole
        - !Ref PolicyListObjectsInBucketRoot
        - !Ref PolicyListObjectsInConfig
        - !Ref PolicyListFoldersInOpenChannels
        - !Ref PolicyListObjectsInOpenChannels
        - !Ref PolicyObjectCreationInOpenChannels
        - !Ref PolicyListFoldersInClosedChannels
        - !Ref PolicyListObjectsInClosedChannels
        - !Ref PolicyObjectCreationInClosedChannels

  PolicyShowAllBucketsOnConsole:
    Type: AWS::IAM::ManagedPolicy
    Description: Allow users to see all buckets in the AWS console
    Properties:
      ManagedPolicyName: ShowAllBucketsOnConsole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - s3:GetBucketLocation
              - s3:ListAllMyBuckets
            Resource: "*"

  PolicyListObjectsInBucketRoot:
    Type: AWS::IAM::ManagedPolicy
    Description: Allow users to see the top bucket content in the AWS console
    Properties:
      ManagedPolicyName: ListObjectsInBucketRoot
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - s3:ListBucket
            Resource: !GetAtt ContentsBucket.Arn
            Condition:
              StringEquals:
                s3:prefix: ""
                s3:delimiter: "/"

  PolicyListObjectsInConfig:
    Type: AWS::IAM::ManagedPolicy
    Description: Allow browsing the config directory
    Properties:
      ManagedPolicyName: ListObjectsInConfig
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - s3:ListBucket
            Resource: !GetAtt ContentsBucket.Arn
            Condition:
              StringEquals:
                s3:prefix: "config/"
                s3:delimiter: "/"

  PolicyListFoldersInOpenChannels:
    Type: AWS::IAM::ManagedPolicy
    Description: Allow browsing of open channels
    Properties:
      ManagedPolicyName: ListFoldersInOpenChannels
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - s3:ListBucket
            Resource: !GetAtt ContentsBucket.Arn
            Condition:
              StringEquals:
                s3:prefix: "open/*"
                s3:delimiter: "/"

  PolicyListObjectsInOpenChannels:
    Type: AWS::IAM::ManagedPolicy
    Description: Allow browsing of objects in open channels
    Properties:
      ManagedPolicyName: ListObjectsInOpenChannels
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - s3:ListObjects
            Resource: !Join
              - ""
              - - !GetAtt ContentsBucket.Arn
                - "/open/*"

  PolicyObjectCreationInOpenChannels:
    Type: AWS::IAM::ManagedPolicy
    Description: Allow creation of objects in open channels
    Properties:
      ManagedPolicyName: ObjectCreationInOpenChannels
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - s3:*Object
              - tag:*
            Resource: !Join
              - ""
              - - !GetAtt ContentsBucket.Arn
                - "/open/*/${aws:username}"

  PolicyListFoldersInClosedChannels:
    Type: AWS::IAM::ManagedPolicy
    Description: Allow browsing of closed channels
    Properties:
      ManagedPolicyName: ListFoldersInClosedChannels
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - s3:ListBucket
            Resource: !GetAtt ContentsBucket.Arn
            Condition:
              StringEquals:
                s3:prefix: "closed/*"
                s3:delimiter: "/"

  PolicyListObjectsInClosedChannels:
    Type: AWS::IAM::ManagedPolicy
    Description: Allow browsing of objects in closed channels
    Properties:
      ManagedPolicyName: ListObjectsInClosedChannels
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - s3:ListObjects
            Resource: !Join
              - ""
              - - !GetAtt ContentsBucket.Arn
                - "/closed/*"

  PolicyObjectCreationInClosedChannels:
    Type: AWS::IAM::ManagedPolicy
    Description: Allow creation of objects in closed channels
    Properties:
      ManagedPolicyName: ObjectCreationInClosedChannels
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - s3:*Object
              - tag:*
            Resource: !Join
              - ""
              - - !GetAtt ContentsBucket.Arn
                - "/closed/*/${aws:username}"


Outputs:
  WebURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - WebhostingBucket
          - DomainName
    Description: URL of S3 bucket to hold website content
  WebBucketName:
    Value: !Ref WebhostingBucket
  WebBucketArn:
    Value: !GetAtt WebhostingBucket.Arn
  ContentsBucketName:
    Value: !Ref ContentsBucket
  ContentsBucketArn:
    Value: !GetAtt ContentsBucket.Arn
  