AWSTemplateFormatVersion: 2010-09-09
Description: Setup for Photo-Forum

Resources:
  ContentsBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
  WebhostingBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Delete
  WebHostingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: WebHostingS3BucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref WebhostingBucket
                - /*
      Bucket: !Ref WebhostingBucket


  ForumAdminsGroup:
    Type: AWS::IAM::Group
    Description: Forum-Admins (Moderators)
    Properties:   
      GroupName: !Join
        - "-"
        - - "ForumAdmins"
          - !Ref AWS::Region
      ManagedPolicyArns:
        - !Ref PolicyShowAllBucketsOnConsole
        - !Ref PolicyListObjectsInBucketRoot

  PolicyShowAllBucketsOnConsole:
    Type: AWS::IAM::ManagedPolicy
    Description: Allow users to see all buckets in the AWS console
    Properties:
      ManagedPolicyName: ShowAllBucketsOnConsole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - s3:GetBucketLocation
              - s3:ListAllMyBuckets
            Resource: "*"

  PolicyListObjectsInBucketRoot:
    Type: AWS::IAM::ManagedPolicy
    Description: Allow users to see the top bucket content in the AWS console
    Properties:
      ManagedPolicyName: ListObjectsInBucketRoot
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - s3:ListBucket
            Resource: !GetAtt ContentsBucket.Arn
            Condition:
              StringEquals:
                s3:prefix: ""
                s3:delimiter: "/"


Outputs:
  WebURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - WebhostingBucket
          - DomainName
    Description: URL of S3 bucket to hold website content
