AWSTemplateFormatVersion: 2010-09-09
Description: Setup for Photo-Forum

Resources:
  ContentsBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
  WebhostingBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Delete
  WebHostingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: WebHostingS3BucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref WebhostingBucket
                - /*
      Bucket: !Ref WebhostingBucket
  ForumAdminsGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Join [ "-",  !Ref ForumAdminsGroup, !Ref AWS::Region ]
      Policies:
        - PolicyName: "S3AdminAccess"
          PolicyDocument:
            Id: ContentsS3BucketPolicy
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 's3:ListBucket'
                Resource: !Join 
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref ContentsBucket
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                Resource: !Join 
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref ContentsBucket
                    - /*

Outputs:
  WebsiteURL:
    Value: !GetAtt 
      - WebhostingBucket
      - WebsiteURL
    Description: URL for website hosted on S3
  WebBucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - WebhostingBucket
          - DomainName
    Description: URL of S3 bucket to hold website content
  WebBucketName:
      Value: !Ref WebhostingBucket
