AWSTemplateFormatVersion: 2010-09-09
Description: Setup for Photo-Forum

Resources:
  ForumS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
  ForumWebhostingBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Delete
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: WebHostingS3BucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref ForumWebhostingBucket
                - /*
      Bucket: !Ref ForumWebhostingBucket
  # Example for creating a Cognito User pool:
  #  https://gist.github.com/singledigit/2c4d7232fa96d9e98a3de89cf6ebe7a5


Outputs:
  WebsiteURL:
    Value: !GetAtt 
      - ForumWebhostingBucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - ForumWebhostingBucket
          - DomainName
    Description: Name of S3 bucket to hold website content

