# Site settings
title: Photo forum software for AWS
email: frank@tegtmeyer.net
description: > # this means to ignore newlines until "baseurl:"
  Photo-forum is a set of configuration and software which allows
  everyone to host a forum which acts like a Google+ community.  
  It is designed to be used by groups of photographers but is not
  limited to this.

  One of the goals is to make hosting extremely cheap by
  using only base services of Amazon Web Services (AWS).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://fte378.github.io/photo-forum/"
github_username:  jekyll

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']

# GitHub Flavoured Markdown (GFM)
markdown: kramdown
highlighter: rouge

# GitHub defaults - https://help.github.com/articles/configuring-jekyll/
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
jailed: false
gfm_quirks: paragraph_end
theme: jekyll-theme-cayman
