# Site settings
title: Photo Forum
# email: frank@tegtmeyer.net
description: > # this means to ignore newlines until "baseurl:"
  Self-hosting of Google+-like communities on AWS
baseurl: "/photo-forum" # the subpath of your site, e.g. /blog/
url: "https://fte378.github.io/photo-forum/"
github_username:  fte378

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']

# GitHub Flavoured Markdown (GFM)
markdown: kramdown
highlighter: rouge

# GitHub defaults - https://help.github.com/articles/configuring-jekyll/
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
jailed: false
gfm_quirks: paragraph_end
remote_theme: daattali/beautiful-jekyll

